// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/apis/observabilityopenapiservice"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/openapi"
)

var observabilityOpenAPIClient observabilityopenapiservice.Client

// IngestTraces .
// @router /v1/loop/traces/ingest [POST]
func IngestTraces(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.IngestTraces)
}

// SearchTraceOApi .
// @router /v1/loop/traces/search [POST]
func SearchTraceOApi(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.SearchTraceOApi)
}

// ListSpansOApi .
// @router /v1/loop/spans/search [POST]
func ListSpansOApi(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.ListSpansOApi)
}

// OtelIngestTraces .
// @router /v1/loop/opentelemetry/v1/traces [POST]
func OtelIngestTraces(ctx context.Context, c *app.RequestContext) {
	var err error

	c.Request.Body()
	resp, err := observabilityOpenAPIClient.OtelIngestTraces(ctx, &openapi.OtelIngestTracesRequest{
		Body:            c.Request.Body(),
		ContentType:     c.Request.Header.Get("Content-Type"),
		ContentEncoding: c.Request.Header.Get("Content-Encoding"),
		WorkspaceID:     c.Request.Header.Get("cozeloop-workspace-id"),
	})
	if err != nil {
		_ = c.Error(err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ListTracesOApi .
// @router /v1/loop/traces/list [POST]
func ListTracesOApi(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.ListTracesOApi)
}

// SearchTraceTreeOApi .
// @router /v1/loop/traces/search_tree [POST]
func SearchTraceTreeOApi(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.SearchTraceTreeOApi)
}

// CreateAnnotation .
// @router /v1/loop/annotations/create [POST]
func CreateAnnotation(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.CreateAnnotation)
}

// DeleteAnnotation .
// @router /v1/loop/annotations/delete [DELETE]
func DeleteAnnotation(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.DeleteAnnotation)
}

// ListPreSpanOApi .
// @router /v1/loop/pre_span/search [POST]
func ListPreSpanOApi(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityOpenAPIClient.ListPreSpanOApi)
}
