// Code generated by Kitex v0.13.1. DO NOT EDIT.

package observabilitytraceservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	observability "github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability"
	trace "github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/trace"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListSpans": kitex.NewMethodInfo(
		listSpansHandler,
		newTraceServiceListSpansArgs,
		newTraceServiceListSpansResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListPreSpan": kitex.NewMethodInfo(
		listPreSpanHandler,
		newTraceServiceListPreSpanArgs,
		newTraceServiceListPreSpanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTrace": kitex.NewMethodInfo(
		getTraceHandler,
		newTraceServiceGetTraceArgs,
		newTraceServiceGetTraceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchTraceTree": kitex.NewMethodInfo(
		searchTraceTreeHandler,
		newTraceServiceSearchTraceTreeArgs,
		newTraceServiceSearchTraceTreeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchGetTracesAdvanceInfo": kitex.NewMethodInfo(
		batchGetTracesAdvanceInfoHandler,
		newTraceServiceBatchGetTracesAdvanceInfoArgs,
		newTraceServiceBatchGetTracesAdvanceInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IngestTracesInner": kitex.NewMethodInfo(
		ingestTracesInnerHandler,
		newTraceServiceIngestTracesInnerArgs,
		newTraceServiceIngestTracesInnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTracesMetaInfo": kitex.NewMethodInfo(
		getTracesMetaInfoHandler,
		newTraceServiceGetTracesMetaInfoArgs,
		newTraceServiceGetTracesMetaInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateView": kitex.NewMethodInfo(
		createViewHandler,
		newTraceServiceCreateViewArgs,
		newTraceServiceCreateViewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateView": kitex.NewMethodInfo(
		updateViewHandler,
		newTraceServiceUpdateViewArgs,
		newTraceServiceUpdateViewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteView": kitex.NewMethodInfo(
		deleteViewHandler,
		newTraceServiceDeleteViewArgs,
		newTraceServiceDeleteViewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListViews": kitex.NewMethodInfo(
		listViewsHandler,
		newTraceServiceListViewsArgs,
		newTraceServiceListViewsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateManualAnnotation": kitex.NewMethodInfo(
		createManualAnnotationHandler,
		newTraceServiceCreateManualAnnotationArgs,
		newTraceServiceCreateManualAnnotationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateManualAnnotation": kitex.NewMethodInfo(
		updateManualAnnotationHandler,
		newTraceServiceUpdateManualAnnotationArgs,
		newTraceServiceUpdateManualAnnotationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteManualAnnotation": kitex.NewMethodInfo(
		deleteManualAnnotationHandler,
		newTraceServiceDeleteManualAnnotationArgs,
		newTraceServiceDeleteManualAnnotationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAnnotations": kitex.NewMethodInfo(
		listAnnotationsHandler,
		newTraceServiceListAnnotationsArgs,
		newTraceServiceListAnnotationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ExportTracesToDataset": kitex.NewMethodInfo(
		exportTracesToDatasetHandler,
		newTraceServiceExportTracesToDatasetArgs,
		newTraceServiceExportTracesToDatasetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PreviewExportTracesToDataset": kitex.NewMethodInfo(
		previewExportTracesToDatasetHandler,
		newTraceServicePreviewExportTracesToDatasetArgs,
		newTraceServicePreviewExportTracesToDatasetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeEvaluatorScore": kitex.NewMethodInfo(
		changeEvaluatorScoreHandler,
		newTraceServiceChangeEvaluatorScoreArgs,
		newTraceServiceChangeEvaluatorScoreResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAnnotationEvaluators": kitex.NewMethodInfo(
		listAnnotationEvaluatorsHandler,
		newTraceServiceListAnnotationEvaluatorsArgs,
		newTraceServiceListAnnotationEvaluatorsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ExtractSpanInfo": kitex.NewMethodInfo(
		extractSpanInfoHandler,
		newTraceServiceExtractSpanInfoArgs,
		newTraceServiceExtractSpanInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpsertTrajectoryConfig": kitex.NewMethodInfo(
		upsertTrajectoryConfigHandler,
		newTraceServiceUpsertTrajectoryConfigArgs,
		newTraceServiceUpsertTrajectoryConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTrajectoryConfig": kitex.NewMethodInfo(
		getTrajectoryConfigHandler,
		newTraceServiceGetTrajectoryConfigArgs,
		newTraceServiceGetTrajectoryConfigResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTrajectory": kitex.NewMethodInfo(
		listTrajectoryHandler,
		newTraceServiceListTrajectoryArgs,
		newTraceServiceListTrajectoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	observabilityTraceServiceServiceInfo = NewServiceInfo()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return observabilityTraceServiceServiceInfo
}

// NewServiceInfo creates a new ServiceInfo
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo()
}

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "ObservabilityTraceService"
	handlerType := (*observability.ObservabilityTraceService)(nil)
	extra := map[string]interface{}{
		"PackageName": "observability",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         serviceMethods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func listSpansHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceListSpansArgs)
	realResult := result.(*trace.TraceServiceListSpansResult)
	success, err := handler.(trace.TraceService).ListSpans(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceListSpansArgs() interface{} {
	return trace.NewTraceServiceListSpansArgs()
}

func newTraceServiceListSpansResult() interface{} {
	return trace.NewTraceServiceListSpansResult()
}

func listPreSpanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceListPreSpanArgs)
	realResult := result.(*trace.TraceServiceListPreSpanResult)
	success, err := handler.(trace.TraceService).ListPreSpan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceListPreSpanArgs() interface{} {
	return trace.NewTraceServiceListPreSpanArgs()
}

func newTraceServiceListPreSpanResult() interface{} {
	return trace.NewTraceServiceListPreSpanResult()
}

func getTraceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceGetTraceArgs)
	realResult := result.(*trace.TraceServiceGetTraceResult)
	success, err := handler.(trace.TraceService).GetTrace(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceGetTraceArgs() interface{} {
	return trace.NewTraceServiceGetTraceArgs()
}

func newTraceServiceGetTraceResult() interface{} {
	return trace.NewTraceServiceGetTraceResult()
}

func searchTraceTreeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceSearchTraceTreeArgs)
	realResult := result.(*trace.TraceServiceSearchTraceTreeResult)
	success, err := handler.(trace.TraceService).SearchTraceTree(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceSearchTraceTreeArgs() interface{} {
	return trace.NewTraceServiceSearchTraceTreeArgs()
}

func newTraceServiceSearchTraceTreeResult() interface{} {
	return trace.NewTraceServiceSearchTraceTreeResult()
}

func batchGetTracesAdvanceInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceBatchGetTracesAdvanceInfoArgs)
	realResult := result.(*trace.TraceServiceBatchGetTracesAdvanceInfoResult)
	success, err := handler.(trace.TraceService).BatchGetTracesAdvanceInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceBatchGetTracesAdvanceInfoArgs() interface{} {
	return trace.NewTraceServiceBatchGetTracesAdvanceInfoArgs()
}

func newTraceServiceBatchGetTracesAdvanceInfoResult() interface{} {
	return trace.NewTraceServiceBatchGetTracesAdvanceInfoResult()
}

func ingestTracesInnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceIngestTracesInnerArgs)
	realResult := result.(*trace.TraceServiceIngestTracesInnerResult)
	success, err := handler.(trace.TraceService).IngestTracesInner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceIngestTracesInnerArgs() interface{} {
	return trace.NewTraceServiceIngestTracesInnerArgs()
}

func newTraceServiceIngestTracesInnerResult() interface{} {
	return trace.NewTraceServiceIngestTracesInnerResult()
}

func getTracesMetaInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceGetTracesMetaInfoArgs)
	realResult := result.(*trace.TraceServiceGetTracesMetaInfoResult)
	success, err := handler.(trace.TraceService).GetTracesMetaInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceGetTracesMetaInfoArgs() interface{} {
	return trace.NewTraceServiceGetTracesMetaInfoArgs()
}

func newTraceServiceGetTracesMetaInfoResult() interface{} {
	return trace.NewTraceServiceGetTracesMetaInfoResult()
}

func createViewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceCreateViewArgs)
	realResult := result.(*trace.TraceServiceCreateViewResult)
	success, err := handler.(trace.TraceService).CreateView(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceCreateViewArgs() interface{} {
	return trace.NewTraceServiceCreateViewArgs()
}

func newTraceServiceCreateViewResult() interface{} {
	return trace.NewTraceServiceCreateViewResult()
}

func updateViewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceUpdateViewArgs)
	realResult := result.(*trace.TraceServiceUpdateViewResult)
	success, err := handler.(trace.TraceService).UpdateView(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceUpdateViewArgs() interface{} {
	return trace.NewTraceServiceUpdateViewArgs()
}

func newTraceServiceUpdateViewResult() interface{} {
	return trace.NewTraceServiceUpdateViewResult()
}

func deleteViewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceDeleteViewArgs)
	realResult := result.(*trace.TraceServiceDeleteViewResult)
	success, err := handler.(trace.TraceService).DeleteView(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceDeleteViewArgs() interface{} {
	return trace.NewTraceServiceDeleteViewArgs()
}

func newTraceServiceDeleteViewResult() interface{} {
	return trace.NewTraceServiceDeleteViewResult()
}

func listViewsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceListViewsArgs)
	realResult := result.(*trace.TraceServiceListViewsResult)
	success, err := handler.(trace.TraceService).ListViews(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceListViewsArgs() interface{} {
	return trace.NewTraceServiceListViewsArgs()
}

func newTraceServiceListViewsResult() interface{} {
	return trace.NewTraceServiceListViewsResult()
}

func createManualAnnotationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceCreateManualAnnotationArgs)
	realResult := result.(*trace.TraceServiceCreateManualAnnotationResult)
	success, err := handler.(trace.TraceService).CreateManualAnnotation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceCreateManualAnnotationArgs() interface{} {
	return trace.NewTraceServiceCreateManualAnnotationArgs()
}

func newTraceServiceCreateManualAnnotationResult() interface{} {
	return trace.NewTraceServiceCreateManualAnnotationResult()
}

func updateManualAnnotationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceUpdateManualAnnotationArgs)
	realResult := result.(*trace.TraceServiceUpdateManualAnnotationResult)
	success, err := handler.(trace.TraceService).UpdateManualAnnotation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceUpdateManualAnnotationArgs() interface{} {
	return trace.NewTraceServiceUpdateManualAnnotationArgs()
}

func newTraceServiceUpdateManualAnnotationResult() interface{} {
	return trace.NewTraceServiceUpdateManualAnnotationResult()
}

func deleteManualAnnotationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceDeleteManualAnnotationArgs)
	realResult := result.(*trace.TraceServiceDeleteManualAnnotationResult)
	success, err := handler.(trace.TraceService).DeleteManualAnnotation(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceDeleteManualAnnotationArgs() interface{} {
	return trace.NewTraceServiceDeleteManualAnnotationArgs()
}

func newTraceServiceDeleteManualAnnotationResult() interface{} {
	return trace.NewTraceServiceDeleteManualAnnotationResult()
}

func listAnnotationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceListAnnotationsArgs)
	realResult := result.(*trace.TraceServiceListAnnotationsResult)
	success, err := handler.(trace.TraceService).ListAnnotations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceListAnnotationsArgs() interface{} {
	return trace.NewTraceServiceListAnnotationsArgs()
}

func newTraceServiceListAnnotationsResult() interface{} {
	return trace.NewTraceServiceListAnnotationsResult()
}

func exportTracesToDatasetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceExportTracesToDatasetArgs)
	realResult := result.(*trace.TraceServiceExportTracesToDatasetResult)
	success, err := handler.(trace.TraceService).ExportTracesToDataset(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceExportTracesToDatasetArgs() interface{} {
	return trace.NewTraceServiceExportTracesToDatasetArgs()
}

func newTraceServiceExportTracesToDatasetResult() interface{} {
	return trace.NewTraceServiceExportTracesToDatasetResult()
}

func previewExportTracesToDatasetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServicePreviewExportTracesToDatasetArgs)
	realResult := result.(*trace.TraceServicePreviewExportTracesToDatasetResult)
	success, err := handler.(trace.TraceService).PreviewExportTracesToDataset(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServicePreviewExportTracesToDatasetArgs() interface{} {
	return trace.NewTraceServicePreviewExportTracesToDatasetArgs()
}

func newTraceServicePreviewExportTracesToDatasetResult() interface{} {
	return trace.NewTraceServicePreviewExportTracesToDatasetResult()
}

func changeEvaluatorScoreHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceChangeEvaluatorScoreArgs)
	realResult := result.(*trace.TraceServiceChangeEvaluatorScoreResult)
	success, err := handler.(trace.TraceService).ChangeEvaluatorScore(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceChangeEvaluatorScoreArgs() interface{} {
	return trace.NewTraceServiceChangeEvaluatorScoreArgs()
}

func newTraceServiceChangeEvaluatorScoreResult() interface{} {
	return trace.NewTraceServiceChangeEvaluatorScoreResult()
}

func listAnnotationEvaluatorsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceListAnnotationEvaluatorsArgs)
	realResult := result.(*trace.TraceServiceListAnnotationEvaluatorsResult)
	success, err := handler.(trace.TraceService).ListAnnotationEvaluators(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceListAnnotationEvaluatorsArgs() interface{} {
	return trace.NewTraceServiceListAnnotationEvaluatorsArgs()
}

func newTraceServiceListAnnotationEvaluatorsResult() interface{} {
	return trace.NewTraceServiceListAnnotationEvaluatorsResult()
}

func extractSpanInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceExtractSpanInfoArgs)
	realResult := result.(*trace.TraceServiceExtractSpanInfoResult)
	success, err := handler.(trace.TraceService).ExtractSpanInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceExtractSpanInfoArgs() interface{} {
	return trace.NewTraceServiceExtractSpanInfoArgs()
}

func newTraceServiceExtractSpanInfoResult() interface{} {
	return trace.NewTraceServiceExtractSpanInfoResult()
}

func upsertTrajectoryConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceUpsertTrajectoryConfigArgs)
	realResult := result.(*trace.TraceServiceUpsertTrajectoryConfigResult)
	success, err := handler.(trace.TraceService).UpsertTrajectoryConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceUpsertTrajectoryConfigArgs() interface{} {
	return trace.NewTraceServiceUpsertTrajectoryConfigArgs()
}

func newTraceServiceUpsertTrajectoryConfigResult() interface{} {
	return trace.NewTraceServiceUpsertTrajectoryConfigResult()
}

func getTrajectoryConfigHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceGetTrajectoryConfigArgs)
	realResult := result.(*trace.TraceServiceGetTrajectoryConfigResult)
	success, err := handler.(trace.TraceService).GetTrajectoryConfig(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceGetTrajectoryConfigArgs() interface{} {
	return trace.NewTraceServiceGetTrajectoryConfigArgs()
}

func newTraceServiceGetTrajectoryConfigResult() interface{} {
	return trace.NewTraceServiceGetTrajectoryConfigResult()
}

func listTrajectoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trace.TraceServiceListTrajectoryArgs)
	realResult := result.(*trace.TraceServiceListTrajectoryResult)
	success, err := handler.(trace.TraceService).ListTrajectory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newTraceServiceListTrajectoryArgs() interface{} {
	return trace.NewTraceServiceListTrajectoryArgs()
}

func newTraceServiceListTrajectoryResult() interface{} {
	return trace.NewTraceServiceListTrajectoryResult()
}

type kClient struct {
	c  client.Client
	sc client.Streaming
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c:  c,
		sc: c.(client.Streaming),
	}
}

func (p *kClient) ListSpans(ctx context.Context, req *trace.ListSpansRequest) (r *trace.ListSpansResponse, err error) {
	var _args trace.TraceServiceListSpansArgs
	_args.Req = req
	var _result trace.TraceServiceListSpansResult
	if err = p.c.Call(ctx, "ListSpans", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPreSpan(ctx context.Context, req *trace.ListPreSpanRequest) (r *trace.ListPreSpanResponse, err error) {
	var _args trace.TraceServiceListPreSpanArgs
	_args.Req = req
	var _result trace.TraceServiceListPreSpanResult
	if err = p.c.Call(ctx, "ListPreSpan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTrace(ctx context.Context, req *trace.GetTraceRequest) (r *trace.GetTraceResponse, err error) {
	var _args trace.TraceServiceGetTraceArgs
	_args.Req = req
	var _result trace.TraceServiceGetTraceResult
	if err = p.c.Call(ctx, "GetTrace", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchTraceTree(ctx context.Context, req *trace.SearchTraceTreeRequest) (r *trace.SearchTraceTreeResponse, err error) {
	var _args trace.TraceServiceSearchTraceTreeArgs
	_args.Req = req
	var _result trace.TraceServiceSearchTraceTreeResult
	if err = p.c.Call(ctx, "SearchTraceTree", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetTracesAdvanceInfo(ctx context.Context, req *trace.BatchGetTracesAdvanceInfoRequest) (r *trace.BatchGetTracesAdvanceInfoResponse, err error) {
	var _args trace.TraceServiceBatchGetTracesAdvanceInfoArgs
	_args.Req = req
	var _result trace.TraceServiceBatchGetTracesAdvanceInfoResult
	if err = p.c.Call(ctx, "BatchGetTracesAdvanceInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IngestTracesInner(ctx context.Context, req *trace.IngestTracesRequest) (r *trace.IngestTracesResponse, err error) {
	var _args trace.TraceServiceIngestTracesInnerArgs
	_args.Req = req
	var _result trace.TraceServiceIngestTracesInnerResult
	if err = p.c.Call(ctx, "IngestTracesInner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTracesMetaInfo(ctx context.Context, req *trace.GetTracesMetaInfoRequest) (r *trace.GetTracesMetaInfoResponse, err error) {
	var _args trace.TraceServiceGetTracesMetaInfoArgs
	_args.Req = req
	var _result trace.TraceServiceGetTracesMetaInfoResult
	if err = p.c.Call(ctx, "GetTracesMetaInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateView(ctx context.Context, req *trace.CreateViewRequest) (r *trace.CreateViewResponse, err error) {
	var _args trace.TraceServiceCreateViewArgs
	_args.Req = req
	var _result trace.TraceServiceCreateViewResult
	if err = p.c.Call(ctx, "CreateView", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateView(ctx context.Context, req *trace.UpdateViewRequest) (r *trace.UpdateViewResponse, err error) {
	var _args trace.TraceServiceUpdateViewArgs
	_args.Req = req
	var _result trace.TraceServiceUpdateViewResult
	if err = p.c.Call(ctx, "UpdateView", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteView(ctx context.Context, req *trace.DeleteViewRequest) (r *trace.DeleteViewResponse, err error) {
	var _args trace.TraceServiceDeleteViewArgs
	_args.Req = req
	var _result trace.TraceServiceDeleteViewResult
	if err = p.c.Call(ctx, "DeleteView", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListViews(ctx context.Context, req *trace.ListViewsRequest) (r *trace.ListViewsResponse, err error) {
	var _args trace.TraceServiceListViewsArgs
	_args.Req = req
	var _result trace.TraceServiceListViewsResult
	if err = p.c.Call(ctx, "ListViews", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateManualAnnotation(ctx context.Context, req *trace.CreateManualAnnotationRequest) (r *trace.CreateManualAnnotationResponse, err error) {
	var _args trace.TraceServiceCreateManualAnnotationArgs
	_args.Req = req
	var _result trace.TraceServiceCreateManualAnnotationResult
	if err = p.c.Call(ctx, "CreateManualAnnotation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateManualAnnotation(ctx context.Context, req *trace.UpdateManualAnnotationRequest) (r *trace.UpdateManualAnnotationResponse, err error) {
	var _args trace.TraceServiceUpdateManualAnnotationArgs
	_args.Req = req
	var _result trace.TraceServiceUpdateManualAnnotationResult
	if err = p.c.Call(ctx, "UpdateManualAnnotation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteManualAnnotation(ctx context.Context, req *trace.DeleteManualAnnotationRequest) (r *trace.DeleteManualAnnotationResponse, err error) {
	var _args trace.TraceServiceDeleteManualAnnotationArgs
	_args.Req = req
	var _result trace.TraceServiceDeleteManualAnnotationResult
	if err = p.c.Call(ctx, "DeleteManualAnnotation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAnnotations(ctx context.Context, req *trace.ListAnnotationsRequest) (r *trace.ListAnnotationsResponse, err error) {
	var _args trace.TraceServiceListAnnotationsArgs
	_args.Req = req
	var _result trace.TraceServiceListAnnotationsResult
	if err = p.c.Call(ctx, "ListAnnotations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ExportTracesToDataset(ctx context.Context, req *trace.ExportTracesToDatasetRequest) (r *trace.ExportTracesToDatasetResponse, err error) {
	var _args trace.TraceServiceExportTracesToDatasetArgs
	_args.Req = req
	var _result trace.TraceServiceExportTracesToDatasetResult
	if err = p.c.Call(ctx, "ExportTracesToDataset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PreviewExportTracesToDataset(ctx context.Context, req *trace.PreviewExportTracesToDatasetRequest) (r *trace.PreviewExportTracesToDatasetResponse, err error) {
	var _args trace.TraceServicePreviewExportTracesToDatasetArgs
	_args.Req = req
	var _result trace.TraceServicePreviewExportTracesToDatasetResult
	if err = p.c.Call(ctx, "PreviewExportTracesToDataset", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeEvaluatorScore(ctx context.Context, req *trace.ChangeEvaluatorScoreRequest) (r *trace.ChangeEvaluatorScoreResponse, err error) {
	var _args trace.TraceServiceChangeEvaluatorScoreArgs
	_args.Req = req
	var _result trace.TraceServiceChangeEvaluatorScoreResult
	if err = p.c.Call(ctx, "ChangeEvaluatorScore", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAnnotationEvaluators(ctx context.Context, req *trace.ListAnnotationEvaluatorsRequest) (r *trace.ListAnnotationEvaluatorsResponse, err error) {
	var _args trace.TraceServiceListAnnotationEvaluatorsArgs
	_args.Req = req
	var _result trace.TraceServiceListAnnotationEvaluatorsResult
	if err = p.c.Call(ctx, "ListAnnotationEvaluators", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ExtractSpanInfo(ctx context.Context, req *trace.ExtractSpanInfoRequest) (r *trace.ExtractSpanInfoResponse, err error) {
	var _args trace.TraceServiceExtractSpanInfoArgs
	_args.Req = req
	var _result trace.TraceServiceExtractSpanInfoResult
	if err = p.c.Call(ctx, "ExtractSpanInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpsertTrajectoryConfig(ctx context.Context, req *trace.UpsertTrajectoryConfigRequest) (r *trace.UpsertTrajectoryConfigResponse, err error) {
	var _args trace.TraceServiceUpsertTrajectoryConfigArgs
	_args.Req = req
	var _result trace.TraceServiceUpsertTrajectoryConfigResult
	if err = p.c.Call(ctx, "UpsertTrajectoryConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTrajectoryConfig(ctx context.Context, req *trace.GetTrajectoryConfigRequest) (r *trace.GetTrajectoryConfigResponse, err error) {
	var _args trace.TraceServiceGetTrajectoryConfigArgs
	_args.Req = req
	var _result trace.TraceServiceGetTrajectoryConfigResult
	if err = p.c.Call(ctx, "GetTrajectoryConfig", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTrajectory(ctx context.Context, req *trace.ListTrajectoryRequest) (r *trace.ListTrajectoryResponse, err error) {
	var _args trace.TraceServiceListTrajectoryArgs
	_args.Req = req
	var _result trace.TraceServiceListTrajectoryResult
	if err = p.c.Call(ctx, "ListTrajectory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
