// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/metric/repo (interfaces: IOfflineMetricRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/offline_metrics.go -package=mocks . IOfflineMetricRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/observability/domain/metric/entity"
	repo "github.com/coze-dev/coze-loop/backend/modules/observability/domain/metric/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockIOfflineMetricRepo is a mock of IOfflineMetricRepo interface.
type MockIOfflineMetricRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIOfflineMetricRepoMockRecorder
	isgomock struct{}
}

// MockIOfflineMetricRepoMockRecorder is the mock recorder for MockIOfflineMetricRepo.
type MockIOfflineMetricRepoMockRecorder struct {
	mock *MockIOfflineMetricRepo
}

// NewMockIOfflineMetricRepo creates a new mock instance.
func NewMockIOfflineMetricRepo(ctrl *gomock.Controller) *MockIOfflineMetricRepo {
	mock := &MockIOfflineMetricRepo{ctrl: ctrl}
	mock.recorder = &MockIOfflineMetricRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOfflineMetricRepo) EXPECT() *MockIOfflineMetricRepoMockRecorder {
	return m.recorder
}

// GetMetrics mocks base method.
func (m *MockIOfflineMetricRepo) GetMetrics(ctx context.Context, param *repo.GetMetricsParam) (*repo.GetMetricsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", ctx, param)
	ret0, _ := ret[0].(*repo.GetMetricsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockIOfflineMetricRepoMockRecorder) GetMetrics(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockIOfflineMetricRepo)(nil).GetMetrics), ctx, param)
}

// InsertMetrics mocks base method.
func (m *MockIOfflineMetricRepo) InsertMetrics(ctx context.Context, events []*entity.MetricEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMetrics", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMetrics indicates an expected call of InsertMetrics.
func (mr *MockIOfflineMetricRepoMockRecorder) InsertMetrics(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMetrics", reflect.TypeOf((*MockIOfflineMetricRepo)(nil).InsertMetrics), ctx, events)
}
