// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNamePromptBasic = "prompt_basic"

// PromptBasic Prompt基础表
type PromptBasic struct {
	ID               int64                 `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                                                                         // 主键ID
	SpaceID          int64                 `gorm:"column:space_id;type:bigint(20) unsigned;not null;uniqueIndex:uniq_space_id_prompt_key_deleted_at,priority:1;index:idx_pid_ptype_delat,priority:1;comment:空间ID" json:"space_id"`                                                  // 空间ID
	PromptKey        string                `gorm:"column:prompt_key;type:varchar(128);not null;uniqueIndex:uniq_space_id_prompt_key_deleted_at,priority:2;comment:Prompt key" json:"prompt_key"`                                                                                    // Prompt key
	Name             string                `gorm:"column:name;type:varchar(128);not null;comment:Prompt名称" json:"name"`                                                                                                                                                             // Prompt名称
	Description      string                `gorm:"column:description;type:varchar(1024);not null;comment:描述" json:"description"`                                                                                                                                                    // 描述
	CreatedBy        string                `gorm:"column:created_by;type:varchar(128);not null;comment:创建人" json:"created_by"`                                                                                                                                                      // 创建人
	UpdatedBy        string                `gorm:"column:updated_by;type:varchar(128);not null;comment:更新人" json:"updated_by"`                                                                                                                                                      // 更新人
	LatestVersion    string                `gorm:"column:latest_version;type:varchar(128);not null;comment:最新版本" json:"latest_version"`                                                                                                                                             // 最新版本
	LatestCommitTime *time.Time            `gorm:"column:latest_commit_time;type:datetime;comment:最新提交时间" json:"latest_commit_time"`                                                                                                                                                // 最新提交时间
	CreatedAt        time.Time             `gorm:"column:created_at;type:datetime;not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                                               // 创建时间
	UpdatedAt        time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                                                                               // 更新时间
	DeletedAt        soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint(20);not null;uniqueIndex:uniq_space_id_prompt_key_deleted_at,priority:3;index:idx_pid_ptype_delat,priority:3;column:deleted_at;not null;default:0;softDelete:milli;comment:删除时间" json:"deleted_at"` // 删除时间
	PromptType       string                `gorm:"column:prompt_type;type:varchar(64);not null;index:idx_pid_ptype_delat,priority:2;default:normal;comment:Prompt类型" json:"prompt_type"`                                                                                            // Prompt类型
	SecurityLevel    string                `gorm:"column:security_level;type:varchar(64);not null;default:L3;comment:security level" json:"security_level"`                                                                                                                         // security level
}

// TableName PromptBasic's table name
func (*PromptBasic) TableName() string {
	return TableNamePromptBasic
}
