// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                            db,
		ObservabilityTask:             newObservabilityTask(db, opts...),
		ObservabilityTaskRun:          newObservabilityTaskRun(db, opts...),
		ObservabilityTrajectoryConfig: newObservabilityTrajectoryConfig(db, opts...),
		ObservabilityView:             newObservabilityView(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ObservabilityTask             observabilityTask
	ObservabilityTaskRun          observabilityTaskRun
	ObservabilityTrajectoryConfig observabilityTrajectoryConfig
	ObservabilityView             observabilityView
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                            db,
		ObservabilityTask:             q.ObservabilityTask.clone(db),
		ObservabilityTaskRun:          q.ObservabilityTaskRun.clone(db),
		ObservabilityTrajectoryConfig: q.ObservabilityTrajectoryConfig.clone(db),
		ObservabilityView:             q.ObservabilityView.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                            db,
		ObservabilityTask:             q.ObservabilityTask.replaceDB(db),
		ObservabilityTaskRun:          q.ObservabilityTaskRun.replaceDB(db),
		ObservabilityTrajectoryConfig: q.ObservabilityTrajectoryConfig.replaceDB(db),
		ObservabilityView:             q.ObservabilityView.replaceDB(db),
	}
}

type queryCtx struct {
	ObservabilityTask             *observabilityTaskDo
	ObservabilityTaskRun          *observabilityTaskRunDo
	ObservabilityTrajectoryConfig *observabilityTrajectoryConfigDo
	ObservabilityView             *observabilityViewDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ObservabilityTask:             q.ObservabilityTask.WithContext(ctx),
		ObservabilityTaskRun:          q.ObservabilityTaskRun.WithContext(ctx),
		ObservabilityTrajectoryConfig: q.ObservabilityTrajectoryConfig.WithContext(ctx),
		ObservabilityView:             q.ObservabilityView.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
