// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package tool

import (
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"strings"
)

const (
	PublicDraftVersion = "$PublicDraft"
)

type Tool struct {
	ID          *int64            `thrift:"id,1,optional" frugal:"1,optional,i64" json:"id" form:"id" query:"id"`
	WorkspaceID *int64            `thrift:"workspace_id,2,optional" frugal:"2,optional,i64" json:"workspace_id" form:"workspace_id" query:"workspace_id"`
	ToolBasic   *ToolBasic        `thrift:"tool_basic,3,optional" frugal:"3,optional,ToolBasic" form:"tool_basic" json:"tool_basic,omitempty" query:"tool_basic"`
	ToolCommit  *ToolCommit       `thrift:"tool_commit,4,optional" frugal:"4,optional,ToolCommit" form:"tool_commit" json:"tool_commit,omitempty" query:"tool_commit"`
	ExtInfos    map[string]string `thrift:"ext_infos,255,optional" frugal:"255,optional,map<string:string>" form:"ext_infos" json:"ext_infos,omitempty" query:"ext_infos"`
}

func NewTool() *Tool {
	return &Tool{}
}

func (p *Tool) InitDefault() {
}

var Tool_ID_DEFAULT int64

func (p *Tool) GetID() (v int64) {
	if p == nil {
		return
	}
	if !p.IsSetID() {
		return Tool_ID_DEFAULT
	}
	return *p.ID
}

var Tool_WorkspaceID_DEFAULT int64

func (p *Tool) GetWorkspaceID() (v int64) {
	if p == nil {
		return
	}
	if !p.IsSetWorkspaceID() {
		return Tool_WorkspaceID_DEFAULT
	}
	return *p.WorkspaceID
}

var Tool_ToolBasic_DEFAULT *ToolBasic

func (p *Tool) GetToolBasic() (v *ToolBasic) {
	if p == nil {
		return
	}
	if !p.IsSetToolBasic() {
		return Tool_ToolBasic_DEFAULT
	}
	return p.ToolBasic
}

var Tool_ToolCommit_DEFAULT *ToolCommit

func (p *Tool) GetToolCommit() (v *ToolCommit) {
	if p == nil {
		return
	}
	if !p.IsSetToolCommit() {
		return Tool_ToolCommit_DEFAULT
	}
	return p.ToolCommit
}

var Tool_ExtInfos_DEFAULT map[string]string

func (p *Tool) GetExtInfos() (v map[string]string) {
	if p == nil {
		return
	}
	if !p.IsSetExtInfos() {
		return Tool_ExtInfos_DEFAULT
	}
	return p.ExtInfos
}
func (p *Tool) SetID(val *int64) {
	p.ID = val
}
func (p *Tool) SetWorkspaceID(val *int64) {
	p.WorkspaceID = val
}
func (p *Tool) SetToolBasic(val *ToolBasic) {
	p.ToolBasic = val
}
func (p *Tool) SetToolCommit(val *ToolCommit) {
	p.ToolCommit = val
}
func (p *Tool) SetExtInfos(val map[string]string) {
	p.ExtInfos = val
}

var fieldIDToName_Tool = map[int16]string{
	1:   "id",
	2:   "workspace_id",
	3:   "tool_basic",
	4:   "tool_commit",
	255: "ext_infos",
}

func (p *Tool) IsSetID() bool {
	return p.ID != nil
}

func (p *Tool) IsSetWorkspaceID() bool {
	return p.WorkspaceID != nil
}

func (p *Tool) IsSetToolBasic() bool {
	return p.ToolBasic != nil
}

func (p *Tool) IsSetToolCommit() bool {
	return p.ToolCommit != nil
}

func (p *Tool) IsSetExtInfos() bool {
	return p.ExtInfos != nil
}

func (p *Tool) Read(iprot thrift.TProtocol) (err error) {
	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 255:
			if fieldTypeId == thrift.MAP {
				if err = p.ReadField255(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_Tool[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *Tool) ReadField1(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ID = _field
	return nil
}
func (p *Tool) ReadField2(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.WorkspaceID = _field
	return nil
}
func (p *Tool) ReadField3(iprot thrift.TProtocol) error {
	_field := NewToolBasic()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.ToolBasic = _field
	return nil
}
func (p *Tool) ReadField4(iprot thrift.TProtocol) error {
	_field := NewToolCommit()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.ToolCommit = _field
	return nil
}
func (p *Tool) ReadField255(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return err
	}
	_field := make(map[string]string, size)
	for i := 0; i < size; i++ {
		var _key string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_key = v
		}

		var _val string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_val = v
		}

		_field[_key] = _val
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return err
	}
	p.ExtInfos = _field
	return nil
}

func (p *Tool) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("Tool"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField255(oprot); err != nil {
			fieldId = 255
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *Tool) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetID() {
		if err = oprot.WriteFieldBegin("id", thrift.I64, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.ID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *Tool) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetWorkspaceID() {
		if err = oprot.WriteFieldBegin("workspace_id", thrift.I64, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.WorkspaceID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *Tool) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetToolBasic() {
		if err = oprot.WriteFieldBegin("tool_basic", thrift.STRUCT, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.ToolBasic.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}
func (p *Tool) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetToolCommit() {
		if err = oprot.WriteFieldBegin("tool_commit", thrift.STRUCT, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.ToolCommit.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}
func (p *Tool) writeField255(oprot thrift.TProtocol) (err error) {
	if p.IsSetExtInfos() {
		if err = oprot.WriteFieldBegin("ext_infos", thrift.MAP, 255); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.ExtInfos)); err != nil {
			return err
		}
		for k, v := range p.ExtInfos {
			if err := oprot.WriteString(k); err != nil {
				return err
			}
			if err := oprot.WriteString(v); err != nil {
				return err
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 end error: ", p), err)
}

func (p *Tool) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Tool(%+v)", *p)

}

func (p *Tool) DeepEqual(ano *Tool) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.ID) {
		return false
	}
	if !p.Field2DeepEqual(ano.WorkspaceID) {
		return false
	}
	if !p.Field3DeepEqual(ano.ToolBasic) {
		return false
	}
	if !p.Field4DeepEqual(ano.ToolCommit) {
		return false
	}
	if !p.Field255DeepEqual(ano.ExtInfos) {
		return false
	}
	return true
}

func (p *Tool) Field1DeepEqual(src *int64) bool {

	if p.ID == src {
		return true
	} else if p.ID == nil || src == nil {
		return false
	}
	if *p.ID != *src {
		return false
	}
	return true
}
func (p *Tool) Field2DeepEqual(src *int64) bool {

	if p.WorkspaceID == src {
		return true
	} else if p.WorkspaceID == nil || src == nil {
		return false
	}
	if *p.WorkspaceID != *src {
		return false
	}
	return true
}
func (p *Tool) Field3DeepEqual(src *ToolBasic) bool {

	if !p.ToolBasic.DeepEqual(src) {
		return false
	}
	return true
}
func (p *Tool) Field4DeepEqual(src *ToolCommit) bool {

	if !p.ToolCommit.DeepEqual(src) {
		return false
	}
	return true
}
func (p *Tool) Field255DeepEqual(src map[string]string) bool {

	if len(p.ExtInfos) != len(src) {
		return false
	}
	for k, v := range p.ExtInfos {
		_src := src[k]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}

type ToolBasic struct {
	Name                   *string `thrift:"name,1,optional" frugal:"1,optional,string" form:"name" json:"name,omitempty" query:"name"`
	Description            *string `thrift:"description,2,optional" frugal:"2,optional,string" form:"description" json:"description,omitempty" query:"description"`
	LatestCommittedVersion *string `thrift:"latest_committed_version,3,optional" frugal:"3,optional,string" form:"latest_committed_version" json:"latest_committed_version,omitempty" query:"latest_committed_version"`
	CreatedBy              *string `thrift:"created_by,4,optional" frugal:"4,optional,string" form:"created_by" json:"created_by,omitempty" query:"created_by"`
	UpdatedBy              *string `thrift:"updated_by,5,optional" frugal:"5,optional,string" form:"updated_by" json:"updated_by,omitempty" query:"updated_by"`
	CreatedAt              *int64  `thrift:"created_at,6,optional" frugal:"6,optional,i64" json:"created_at" form:"created_at" query:"created_at"`
	UpdatedAt              *int64  `thrift:"updated_at,7,optional" frugal:"7,optional,i64" json:"updated_at" form:"updated_at" query:"updated_at"`
}

func NewToolBasic() *ToolBasic {
	return &ToolBasic{}
}

func (p *ToolBasic) InitDefault() {
}

var ToolBasic_Name_DEFAULT string

func (p *ToolBasic) GetName() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetName() {
		return ToolBasic_Name_DEFAULT
	}
	return *p.Name
}

var ToolBasic_Description_DEFAULT string

func (p *ToolBasic) GetDescription() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetDescription() {
		return ToolBasic_Description_DEFAULT
	}
	return *p.Description
}

var ToolBasic_LatestCommittedVersion_DEFAULT string

func (p *ToolBasic) GetLatestCommittedVersion() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetLatestCommittedVersion() {
		return ToolBasic_LatestCommittedVersion_DEFAULT
	}
	return *p.LatestCommittedVersion
}

var ToolBasic_CreatedBy_DEFAULT string

func (p *ToolBasic) GetCreatedBy() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetCreatedBy() {
		return ToolBasic_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var ToolBasic_UpdatedBy_DEFAULT string

func (p *ToolBasic) GetUpdatedBy() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetUpdatedBy() {
		return ToolBasic_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var ToolBasic_CreatedAt_DEFAULT int64

func (p *ToolBasic) GetCreatedAt() (v int64) {
	if p == nil {
		return
	}
	if !p.IsSetCreatedAt() {
		return ToolBasic_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var ToolBasic_UpdatedAt_DEFAULT int64

func (p *ToolBasic) GetUpdatedAt() (v int64) {
	if p == nil {
		return
	}
	if !p.IsSetUpdatedAt() {
		return ToolBasic_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *ToolBasic) SetName(val *string) {
	p.Name = val
}
func (p *ToolBasic) SetDescription(val *string) {
	p.Description = val
}
func (p *ToolBasic) SetLatestCommittedVersion(val *string) {
	p.LatestCommittedVersion = val
}
func (p *ToolBasic) SetCreatedBy(val *string) {
	p.CreatedBy = val
}
func (p *ToolBasic) SetUpdatedBy(val *string) {
	p.UpdatedBy = val
}
func (p *ToolBasic) SetCreatedAt(val *int64) {
	p.CreatedAt = val
}
func (p *ToolBasic) SetUpdatedAt(val *int64) {
	p.UpdatedAt = val
}

var fieldIDToName_ToolBasic = map[int16]string{
	1: "name",
	2: "description",
	3: "latest_committed_version",
	4: "created_by",
	5: "updated_by",
	6: "created_at",
	7: "updated_at",
}

func (p *ToolBasic) IsSetName() bool {
	return p.Name != nil
}

func (p *ToolBasic) IsSetDescription() bool {
	return p.Description != nil
}

func (p *ToolBasic) IsSetLatestCommittedVersion() bool {
	return p.LatestCommittedVersion != nil
}

func (p *ToolBasic) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *ToolBasic) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *ToolBasic) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *ToolBasic) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *ToolBasic) Read(iprot thrift.TProtocol) (err error) {
	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ToolBasic[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ToolBasic) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Name = _field
	return nil
}
func (p *ToolBasic) ReadField2(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Description = _field
	return nil
}
func (p *ToolBasic) ReadField3(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.LatestCommittedVersion = _field
	return nil
}
func (p *ToolBasic) ReadField4(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.CreatedBy = _field
	return nil
}
func (p *ToolBasic) ReadField5(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UpdatedBy = _field
	return nil
}
func (p *ToolBasic) ReadField6(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.CreatedAt = _field
	return nil
}
func (p *ToolBasic) ReadField7(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UpdatedAt = _field
	return nil
}

func (p *ToolBasic) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ToolBasic"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ToolBasic) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetName() {
		if err = oprot.WriteFieldBegin("name", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Name); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *ToolBasic) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetDescription() {
		if err = oprot.WriteFieldBegin("description", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Description); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *ToolBasic) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetLatestCommittedVersion() {
		if err = oprot.WriteFieldBegin("latest_committed_version", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.LatestCommittedVersion); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}
func (p *ToolBasic) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreatedBy() {
		if err = oprot.WriteFieldBegin("created_by", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.CreatedBy); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}
func (p *ToolBasic) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetUpdatedBy() {
		if err = oprot.WriteFieldBegin("updated_by", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.UpdatedBy); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}
func (p *ToolBasic) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreatedAt() {
		if err = oprot.WriteFieldBegin("created_at", thrift.I64, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.CreatedAt); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}
func (p *ToolBasic) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetUpdatedAt() {
		if err = oprot.WriteFieldBegin("updated_at", thrift.I64, 7); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.UpdatedAt); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *ToolBasic) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ToolBasic(%+v)", *p)

}

func (p *ToolBasic) DeepEqual(ano *ToolBasic) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Name) {
		return false
	}
	if !p.Field2DeepEqual(ano.Description) {
		return false
	}
	if !p.Field3DeepEqual(ano.LatestCommittedVersion) {
		return false
	}
	if !p.Field4DeepEqual(ano.CreatedBy) {
		return false
	}
	if !p.Field5DeepEqual(ano.UpdatedBy) {
		return false
	}
	if !p.Field6DeepEqual(ano.CreatedAt) {
		return false
	}
	if !p.Field7DeepEqual(ano.UpdatedAt) {
		return false
	}
	return true
}

func (p *ToolBasic) Field1DeepEqual(src *string) bool {

	if p.Name == src {
		return true
	} else if p.Name == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Name, *src) != 0 {
		return false
	}
	return true
}
func (p *ToolBasic) Field2DeepEqual(src *string) bool {

	if p.Description == src {
		return true
	} else if p.Description == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Description, *src) != 0 {
		return false
	}
	return true
}
func (p *ToolBasic) Field3DeepEqual(src *string) bool {

	if p.LatestCommittedVersion == src {
		return true
	} else if p.LatestCommittedVersion == nil || src == nil {
		return false
	}
	if strings.Compare(*p.LatestCommittedVersion, *src) != 0 {
		return false
	}
	return true
}
func (p *ToolBasic) Field4DeepEqual(src *string) bool {

	if p.CreatedBy == src {
		return true
	} else if p.CreatedBy == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CreatedBy, *src) != 0 {
		return false
	}
	return true
}
func (p *ToolBasic) Field5DeepEqual(src *string) bool {

	if p.UpdatedBy == src {
		return true
	} else if p.UpdatedBy == nil || src == nil {
		return false
	}
	if strings.Compare(*p.UpdatedBy, *src) != 0 {
		return false
	}
	return true
}
func (p *ToolBasic) Field6DeepEqual(src *int64) bool {

	if p.CreatedAt == src {
		return true
	} else if p.CreatedAt == nil || src == nil {
		return false
	}
	if *p.CreatedAt != *src {
		return false
	}
	return true
}
func (p *ToolBasic) Field7DeepEqual(src *int64) bool {

	if p.UpdatedAt == src {
		return true
	} else if p.UpdatedAt == nil || src == nil {
		return false
	}
	if *p.UpdatedAt != *src {
		return false
	}
	return true
}

type ToolCommit struct {
	Detail     *ToolDetail `thrift:"detail,1,optional" frugal:"1,optional,ToolDetail" form:"detail" json:"detail,omitempty" query:"detail"`
	CommitInfo *CommitInfo `thrift:"commit_info,2,optional" frugal:"2,optional,CommitInfo" form:"commit_info" json:"commit_info,omitempty" query:"commit_info"`
}

func NewToolCommit() *ToolCommit {
	return &ToolCommit{}
}

func (p *ToolCommit) InitDefault() {
}

var ToolCommit_Detail_DEFAULT *ToolDetail

func (p *ToolCommit) GetDetail() (v *ToolDetail) {
	if p == nil {
		return
	}
	if !p.IsSetDetail() {
		return ToolCommit_Detail_DEFAULT
	}
	return p.Detail
}

var ToolCommit_CommitInfo_DEFAULT *CommitInfo

func (p *ToolCommit) GetCommitInfo() (v *CommitInfo) {
	if p == nil {
		return
	}
	if !p.IsSetCommitInfo() {
		return ToolCommit_CommitInfo_DEFAULT
	}
	return p.CommitInfo
}
func (p *ToolCommit) SetDetail(val *ToolDetail) {
	p.Detail = val
}
func (p *ToolCommit) SetCommitInfo(val *CommitInfo) {
	p.CommitInfo = val
}

var fieldIDToName_ToolCommit = map[int16]string{
	1: "detail",
	2: "commit_info",
}

func (p *ToolCommit) IsSetDetail() bool {
	return p.Detail != nil
}

func (p *ToolCommit) IsSetCommitInfo() bool {
	return p.CommitInfo != nil
}

func (p *ToolCommit) Read(iprot thrift.TProtocol) (err error) {
	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ToolCommit[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ToolCommit) ReadField1(iprot thrift.TProtocol) error {
	_field := NewToolDetail()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Detail = _field
	return nil
}
func (p *ToolCommit) ReadField2(iprot thrift.TProtocol) error {
	_field := NewCommitInfo()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.CommitInfo = _field
	return nil
}

func (p *ToolCommit) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ToolCommit"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ToolCommit) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetDetail() {
		if err = oprot.WriteFieldBegin("detail", thrift.STRUCT, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Detail.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *ToolCommit) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetCommitInfo() {
		if err = oprot.WriteFieldBegin("commit_info", thrift.STRUCT, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.CommitInfo.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *ToolCommit) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ToolCommit(%+v)", *p)

}

func (p *ToolCommit) DeepEqual(ano *ToolCommit) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Detail) {
		return false
	}
	if !p.Field2DeepEqual(ano.CommitInfo) {
		return false
	}
	return true
}

func (p *ToolCommit) Field1DeepEqual(src *ToolDetail) bool {

	if !p.Detail.DeepEqual(src) {
		return false
	}
	return true
}
func (p *ToolCommit) Field2DeepEqual(src *CommitInfo) bool {

	if !p.CommitInfo.DeepEqual(src) {
		return false
	}
	return true
}

type CommitInfo struct {
	Version     *string `thrift:"version,1,optional" frugal:"1,optional,string" form:"version" json:"version,omitempty" query:"version"`
	BaseVersion *string `thrift:"base_version,2,optional" frugal:"2,optional,string" form:"base_version" json:"base_version,omitempty" query:"base_version"`
	Description *string `thrift:"description,3,optional" frugal:"3,optional,string" form:"description" json:"description,omitempty" query:"description"`
	CommittedBy *string `thrift:"committed_by,4,optional" frugal:"4,optional,string" form:"committed_by" json:"committed_by,omitempty" query:"committed_by"`
	CommittedAt *int64  `thrift:"committed_at,5,optional" frugal:"5,optional,i64" json:"committed_at" form:"committed_at" query:"committed_at"`
}

func NewCommitInfo() *CommitInfo {
	return &CommitInfo{}
}

func (p *CommitInfo) InitDefault() {
}

var CommitInfo_Version_DEFAULT string

func (p *CommitInfo) GetVersion() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetVersion() {
		return CommitInfo_Version_DEFAULT
	}
	return *p.Version
}

var CommitInfo_BaseVersion_DEFAULT string

func (p *CommitInfo) GetBaseVersion() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetBaseVersion() {
		return CommitInfo_BaseVersion_DEFAULT
	}
	return *p.BaseVersion
}

var CommitInfo_Description_DEFAULT string

func (p *CommitInfo) GetDescription() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetDescription() {
		return CommitInfo_Description_DEFAULT
	}
	return *p.Description
}

var CommitInfo_CommittedBy_DEFAULT string

func (p *CommitInfo) GetCommittedBy() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetCommittedBy() {
		return CommitInfo_CommittedBy_DEFAULT
	}
	return *p.CommittedBy
}

var CommitInfo_CommittedAt_DEFAULT int64

func (p *CommitInfo) GetCommittedAt() (v int64) {
	if p == nil {
		return
	}
	if !p.IsSetCommittedAt() {
		return CommitInfo_CommittedAt_DEFAULT
	}
	return *p.CommittedAt
}
func (p *CommitInfo) SetVersion(val *string) {
	p.Version = val
}
func (p *CommitInfo) SetBaseVersion(val *string) {
	p.BaseVersion = val
}
func (p *CommitInfo) SetDescription(val *string) {
	p.Description = val
}
func (p *CommitInfo) SetCommittedBy(val *string) {
	p.CommittedBy = val
}
func (p *CommitInfo) SetCommittedAt(val *int64) {
	p.CommittedAt = val
}

var fieldIDToName_CommitInfo = map[int16]string{
	1: "version",
	2: "base_version",
	3: "description",
	4: "committed_by",
	5: "committed_at",
}

func (p *CommitInfo) IsSetVersion() bool {
	return p.Version != nil
}

func (p *CommitInfo) IsSetBaseVersion() bool {
	return p.BaseVersion != nil
}

func (p *CommitInfo) IsSetDescription() bool {
	return p.Description != nil
}

func (p *CommitInfo) IsSetCommittedBy() bool {
	return p.CommittedBy != nil
}

func (p *CommitInfo) IsSetCommittedAt() bool {
	return p.CommittedAt != nil
}

func (p *CommitInfo) Read(iprot thrift.TProtocol) (err error) {
	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_CommitInfo[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *CommitInfo) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Version = _field
	return nil
}
func (p *CommitInfo) ReadField2(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.BaseVersion = _field
	return nil
}
func (p *CommitInfo) ReadField3(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Description = _field
	return nil
}
func (p *CommitInfo) ReadField4(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.CommittedBy = _field
	return nil
}
func (p *CommitInfo) ReadField5(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.CommittedAt = _field
	return nil
}

func (p *CommitInfo) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CommitInfo"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *CommitInfo) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetVersion() {
		if err = oprot.WriteFieldBegin("version", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Version); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *CommitInfo) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetBaseVersion() {
		if err = oprot.WriteFieldBegin("base_version", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.BaseVersion); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *CommitInfo) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetDescription() {
		if err = oprot.WriteFieldBegin("description", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Description); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}
func (p *CommitInfo) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCommittedBy() {
		if err = oprot.WriteFieldBegin("committed_by", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.CommittedBy); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}
func (p *CommitInfo) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetCommittedAt() {
		if err = oprot.WriteFieldBegin("committed_at", thrift.I64, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.CommittedAt); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *CommitInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommitInfo(%+v)", *p)

}

func (p *CommitInfo) DeepEqual(ano *CommitInfo) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Version) {
		return false
	}
	if !p.Field2DeepEqual(ano.BaseVersion) {
		return false
	}
	if !p.Field3DeepEqual(ano.Description) {
		return false
	}
	if !p.Field4DeepEqual(ano.CommittedBy) {
		return false
	}
	if !p.Field5DeepEqual(ano.CommittedAt) {
		return false
	}
	return true
}

func (p *CommitInfo) Field1DeepEqual(src *string) bool {

	if p.Version == src {
		return true
	} else if p.Version == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Version, *src) != 0 {
		return false
	}
	return true
}
func (p *CommitInfo) Field2DeepEqual(src *string) bool {

	if p.BaseVersion == src {
		return true
	} else if p.BaseVersion == nil || src == nil {
		return false
	}
	if strings.Compare(*p.BaseVersion, *src) != 0 {
		return false
	}
	return true
}
func (p *CommitInfo) Field3DeepEqual(src *string) bool {

	if p.Description == src {
		return true
	} else if p.Description == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Description, *src) != 0 {
		return false
	}
	return true
}
func (p *CommitInfo) Field4DeepEqual(src *string) bool {

	if p.CommittedBy == src {
		return true
	} else if p.CommittedBy == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CommittedBy, *src) != 0 {
		return false
	}
	return true
}
func (p *CommitInfo) Field5DeepEqual(src *int64) bool {

	if p.CommittedAt == src {
		return true
	} else if p.CommittedAt == nil || src == nil {
		return false
	}
	if *p.CommittedAt != *src {
		return false
	}
	return true
}

type ToolDetail struct {
	Content  *string           `thrift:"content,1,optional" frugal:"1,optional,string" form:"content" json:"content,omitempty" query:"content"`
	ExtInfos map[string]string `thrift:"ext_infos,255,optional" frugal:"255,optional,map<string:string>" form:"ext_infos" json:"ext_infos,omitempty" query:"ext_infos"`
}

func NewToolDetail() *ToolDetail {
	return &ToolDetail{}
}

func (p *ToolDetail) InitDefault() {
}

var ToolDetail_Content_DEFAULT string

func (p *ToolDetail) GetContent() (v string) {
	if p == nil {
		return
	}
	if !p.IsSetContent() {
		return ToolDetail_Content_DEFAULT
	}
	return *p.Content
}

var ToolDetail_ExtInfos_DEFAULT map[string]string

func (p *ToolDetail) GetExtInfos() (v map[string]string) {
	if p == nil {
		return
	}
	if !p.IsSetExtInfos() {
		return ToolDetail_ExtInfos_DEFAULT
	}
	return p.ExtInfos
}
func (p *ToolDetail) SetContent(val *string) {
	p.Content = val
}
func (p *ToolDetail) SetExtInfos(val map[string]string) {
	p.ExtInfos = val
}

var fieldIDToName_ToolDetail = map[int16]string{
	1:   "content",
	255: "ext_infos",
}

func (p *ToolDetail) IsSetContent() bool {
	return p.Content != nil
}

func (p *ToolDetail) IsSetExtInfos() bool {
	return p.ExtInfos != nil
}

func (p *ToolDetail) Read(iprot thrift.TProtocol) (err error) {
	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 255:
			if fieldTypeId == thrift.MAP {
				if err = p.ReadField255(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ToolDetail[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ToolDetail) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Content = _field
	return nil
}
func (p *ToolDetail) ReadField255(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return err
	}
	_field := make(map[string]string, size)
	for i := 0; i < size; i++ {
		var _key string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_key = v
		}

		var _val string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_val = v
		}

		_field[_key] = _val
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return err
	}
	p.ExtInfos = _field
	return nil
}

func (p *ToolDetail) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ToolDetail"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField255(oprot); err != nil {
			fieldId = 255
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ToolDetail) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetContent() {
		if err = oprot.WriteFieldBegin("content", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Content); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *ToolDetail) writeField255(oprot thrift.TProtocol) (err error) {
	if p.IsSetExtInfos() {
		if err = oprot.WriteFieldBegin("ext_infos", thrift.MAP, 255); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.ExtInfos)); err != nil {
			return err
		}
		for k, v := range p.ExtInfos {
			if err := oprot.WriteString(k); err != nil {
				return err
			}
			if err := oprot.WriteString(v); err != nil {
				return err
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 255 end error: ", p), err)
}

func (p *ToolDetail) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ToolDetail(%+v)", *p)

}

func (p *ToolDetail) DeepEqual(ano *ToolDetail) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Content) {
		return false
	}
	if !p.Field255DeepEqual(ano.ExtInfos) {
		return false
	}
	return true
}

func (p *ToolDetail) Field1DeepEqual(src *string) bool {

	if p.Content == src {
		return true
	} else if p.Content == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Content, *src) != 0 {
		return false
	}
	return true
}
func (p *ToolDetail) Field255DeepEqual(src map[string]string) bool {

	if len(p.ExtInfos) != len(src) {
		return false
	}
	for k, v := range p.ExtInfos {
		_src := src[k]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
