// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/infra/limiter (interfaces: IPlainRateLimiter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/plain_rate_limiter.go -package=mocks . IPlainRateLimiter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	limiter "github.com/coze-dev/coze-loop/backend/infra/limiter"
	gomock "go.uber.org/mock/gomock"
)

// MockIPlainRateLimiter is a mock of IPlainRateLimiter interface.
type MockIPlainRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockIPlainRateLimiterMockRecorder
	isgomock struct{}
}

// MockIPlainRateLimiterMockRecorder is the mock recorder for MockIPlainRateLimiter.
type MockIPlainRateLimiterMockRecorder struct {
	mock *MockIPlainRateLimiter
}

// NewMockIPlainRateLimiter creates a new mock instance.
func NewMockIPlainRateLimiter(ctrl *gomock.Controller) *MockIPlainRateLimiter {
	mock := &MockIPlainRateLimiter{ctrl: ctrl}
	mock.recorder = &MockIPlainRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlainRateLimiter) EXPECT() *MockIPlainRateLimiterMockRecorder {
	return m.recorder
}

// AllowN mocks base method.
func (m *MockIPlainRateLimiter) AllowN(ctx context.Context, key string, n int, opts ...limiter.LimitOptionFn) (*limiter.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, n}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AllowN", varargs...)
	ret0, _ := ret[0].(*limiter.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllowN indicates an expected call of AllowN.
func (mr *MockIPlainRateLimiterMockRecorder) AllowN(ctx, key, n any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, n}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowN", reflect.TypeOf((*MockIPlainRateLimiter)(nil).AllowN), varargs...)
}
