// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/service (interfaces: ITraceExportService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/trace_export_service_mock.go -package=mocks . ITraceExportService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/service"
	gomock "go.uber.org/mock/gomock"
)

// MockITraceExportService is a mock of ITraceExportService interface.
type MockITraceExportService struct {
	ctrl     *gomock.Controller
	recorder *MockITraceExportServiceMockRecorder
	isgomock struct{}
}

// MockITraceExportServiceMockRecorder is the mock recorder for MockITraceExportService.
type MockITraceExportServiceMockRecorder struct {
	mock *MockITraceExportService
}

// NewMockITraceExportService creates a new mock instance.
func NewMockITraceExportService(ctrl *gomock.Controller) *MockITraceExportService {
	mock := &MockITraceExportService{ctrl: ctrl}
	mock.recorder = &MockITraceExportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITraceExportService) EXPECT() *MockITraceExportServiceMockRecorder {
	return m.recorder
}

// ExportTracesToDataset mocks base method.
func (m *MockITraceExportService) ExportTracesToDataset(ctx context.Context, req *service.ExportTracesToDatasetRequest) (*service.ExportTracesToDatasetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportTracesToDataset", ctx, req)
	ret0, _ := ret[0].(*service.ExportTracesToDatasetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportTracesToDataset indicates an expected call of ExportTracesToDataset.
func (mr *MockITraceExportServiceMockRecorder) ExportTracesToDataset(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportTracesToDataset", reflect.TypeOf((*MockITraceExportService)(nil).ExportTracesToDataset), ctx, req)
}

// PreviewExportTracesToDataset mocks base method.
func (m *MockITraceExportService) PreviewExportTracesToDataset(ctx context.Context, req *service.ExportTracesToDatasetRequest) (*service.PreviewExportTracesToDatasetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewExportTracesToDataset", ctx, req)
	ret0, _ := ret[0].(*service.PreviewExportTracesToDatasetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewExportTracesToDataset indicates an expected call of PreviewExportTracesToDataset.
func (mr *MockITraceExportServiceMockRecorder) PreviewExportTracesToDataset(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewExportTracesToDataset", reflect.TypeOf((*MockITraceExportService)(nil).PreviewExportTracesToDataset), ctx, req)
}
