// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/span_context_extractor (interfaces: ISpanContextExtractor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/span_context_extractor.go -package=mocks . ISpanContextExtractor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	loop_span "github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/entity/loop_span"
	gomock "go.uber.org/mock/gomock"
)

// MockISpanContextExtractor is a mock of ISpanContextExtractor interface.
type MockISpanContextExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockISpanContextExtractorMockRecorder
	isgomock struct{}
}

// MockISpanContextExtractorMockRecorder is the mock recorder for MockISpanContextExtractor.
type MockISpanContextExtractorMockRecorder struct {
	mock *MockISpanContextExtractor
}

// NewMockISpanContextExtractor creates a new mock instance.
func NewMockISpanContextExtractor(ctrl *gomock.Controller) *MockISpanContextExtractor {
	mock := &MockISpanContextExtractor{ctrl: ctrl}
	mock.recorder = &MockISpanContextExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISpanContextExtractor) EXPECT() *MockISpanContextExtractorMockRecorder {
	return m.recorder
}

// GetBenefitSource mocks base method.
func (m *MockISpanContextExtractor) GetBenefitSource(ctx context.Context, callType string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBenefitSource", ctx, callType)
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetBenefitSource indicates an expected call of GetBenefitSource.
func (mr *MockISpanContextExtractorMockRecorder) GetBenefitSource(ctx, callType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBenefitSource", reflect.TypeOf((*MockISpanContextExtractor)(nil).GetBenefitSource), ctx, callType)
}

// GetCallType mocks base method.
func (m *MockISpanContextExtractor) GetCallType(ctx context.Context, spans *loop_span.Span) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCallType", ctx, spans)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCallType indicates an expected call of GetCallType.
func (mr *MockISpanContextExtractorMockRecorder) GetCallType(ctx, spans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCallType", reflect.TypeOf((*MockISpanContextExtractor)(nil).GetCallType), ctx, spans)
}
