// Code generated by Validator v0.2.6. DO NOT EDIT.

package metric

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *GetMetricsRequest) IsValid() error {
	if p.WorkspaceID <= int64(0) {
		return fmt.Errorf("field WorkspaceID gt rule failed, current value: %v", p.WorkspaceID)
	}
	if p.StartTime <= int64(0) {
		return fmt.Errorf("field StartTime gt rule failed, current value: %v", p.StartTime)
	}
	if p.EndTime <= int64(0) {
		return fmt.Errorf("field EndTime gt rule failed, current value: %v", p.EndTime)
	}
	if len(p.MetricNames) < int(1) {
		return fmt.Errorf("field MetricNames MinLen rule failed, current value: %v", p.MetricNames)
	}
	if p.Filters != nil {
		if err := p.Filters.IsValid(); err != nil {
			return fmt.Errorf("field Filters not valid, %w", err)
		}
	}
	if p.Compare != nil {
		if err := p.Compare.IsValid(); err != nil {
			return fmt.Errorf("field Compare not valid, %w", err)
		}
	}
	if p.Base != nil {
		if err := p.Base.IsValid(); err != nil {
			return fmt.Errorf("field Base not valid, %w", err)
		}
	}
	return nil
}
func (p *GetMetricsResponse) IsValid() error {
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("field BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *GetDrillDownValuesRequest) IsValid() error {
	if p.WorkspaceID <= int64(0) {
		return fmt.Errorf("field WorkspaceID gt rule failed, current value: %v", p.WorkspaceID)
	}
	if p.StartTime <= int64(0) {
		return fmt.Errorf("field StartTime gt rule failed, current value: %v", p.StartTime)
	}
	if p.EndTime <= int64(0) {
		return fmt.Errorf("field EndTime gt rule failed, current value: %v", p.EndTime)
	}
	if p.Filters != nil {
		if err := p.Filters.IsValid(); err != nil {
			return fmt.Errorf("field Filters not valid, %w", err)
		}
	}
	if p.Base != nil {
		if err := p.Base.IsValid(); err != nil {
			return fmt.Errorf("field Base not valid, %w", err)
		}
	}
	return nil
}
func (p *DrillDownValue) IsValid() error {
	return nil
}
func (p *GetDrillDownValuesResponse) IsValid() error {
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("field BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *TraverseMetricsRequest) IsValid() error {
	if p.Base != nil {
		if err := p.Base.IsValid(); err != nil {
			return fmt.Errorf("field Base not valid, %w", err)
		}
	}
	return nil
}
func (p *TraverseMetricsStatistic) IsValid() error {
	return nil
}
func (p *TraverseMetricsResponse) IsValid() error {
	if p.Statistic != nil {
		if err := p.Statistic.IsValid(); err != nil {
			return fmt.Errorf("field Statistic not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("field BaseResp not valid, %w", err)
		}
	}
	return nil
}
