// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
)

func newToolCommit(db *gorm.DB, opts ...gen.DOOption) toolCommit {
	_toolCommit := toolCommit{}

	_toolCommit.toolCommitDo.UseDB(db, opts...)
	_toolCommit.toolCommitDo.UseModel(&model.ToolCommit{})

	tableName := _toolCommit.toolCommitDo.TableName()
	_toolCommit.ALL = field.NewAsterisk(tableName)
	_toolCommit.ID = field.NewInt64(tableName, "id")
	_toolCommit.SpaceID = field.NewInt64(tableName, "space_id")
	_toolCommit.ToolID = field.NewInt64(tableName, "tool_id")
	_toolCommit.Content = field.NewString(tableName, "content")
	_toolCommit.Version = field.NewString(tableName, "version")
	_toolCommit.BaseVersion = field.NewString(tableName, "base_version")
	_toolCommit.CommittedBy = field.NewString(tableName, "committed_by")
	_toolCommit.Description = field.NewString(tableName, "description")
	_toolCommit.CreatedAt = field.NewTime(tableName, "created_at")
	_toolCommit.UpdatedAt = field.NewTime(tableName, "updated_at")

	_toolCommit.fillFieldMap()

	return _toolCommit
}

// toolCommit 工具版本
type toolCommit struct {
	toolCommitDo toolCommitDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键ID
	SpaceID     field.Int64  // 空间ID
	ToolID      field.Int64  // Tool ID
	Content     field.String // 工具内容
	Version     field.String // 版本
	BaseVersion field.String // 来源版本
	CommittedBy field.String // 提交人
	Description field.String // 提交版本描述
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (t toolCommit) Table(newTableName string) *toolCommit {
	t.toolCommitDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t toolCommit) As(alias string) *toolCommit {
	t.toolCommitDo.DO = *(t.toolCommitDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *toolCommit) updateTableName(table string) *toolCommit {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.SpaceID = field.NewInt64(table, "space_id")
	t.ToolID = field.NewInt64(table, "tool_id")
	t.Content = field.NewString(table, "content")
	t.Version = field.NewString(table, "version")
	t.BaseVersion = field.NewString(table, "base_version")
	t.CommittedBy = field.NewString(table, "committed_by")
	t.Description = field.NewString(table, "description")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *toolCommit) WithContext(ctx context.Context) *toolCommitDo {
	return t.toolCommitDo.WithContext(ctx)
}

func (t toolCommit) TableName() string { return t.toolCommitDo.TableName() }

func (t toolCommit) Alias() string { return t.toolCommitDo.Alias() }

func (t toolCommit) Columns(cols ...field.Expr) gen.Columns { return t.toolCommitDo.Columns(cols...) }

func (t *toolCommit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *toolCommit) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["space_id"] = t.SpaceID
	t.fieldMap["tool_id"] = t.ToolID
	t.fieldMap["content"] = t.Content
	t.fieldMap["version"] = t.Version
	t.fieldMap["base_version"] = t.BaseVersion
	t.fieldMap["committed_by"] = t.CommittedBy
	t.fieldMap["description"] = t.Description
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t toolCommit) clone(db *gorm.DB) toolCommit {
	t.toolCommitDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t toolCommit) replaceDB(db *gorm.DB) toolCommit {
	t.toolCommitDo.ReplaceDB(db)
	return t
}

type toolCommitDo struct{ gen.DO }

func (t toolCommitDo) Debug() *toolCommitDo {
	return t.withDO(t.DO.Debug())
}

func (t toolCommitDo) WithContext(ctx context.Context) *toolCommitDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t toolCommitDo) ReadDB() *toolCommitDo {
	return t.Clauses(dbresolver.Read)
}

func (t toolCommitDo) WriteDB() *toolCommitDo {
	return t.Clauses(dbresolver.Write)
}

func (t toolCommitDo) Session(config *gorm.Session) *toolCommitDo {
	return t.withDO(t.DO.Session(config))
}

func (t toolCommitDo) Clauses(conds ...clause.Expression) *toolCommitDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t toolCommitDo) Returning(value interface{}, columns ...string) *toolCommitDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t toolCommitDo) Not(conds ...gen.Condition) *toolCommitDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t toolCommitDo) Or(conds ...gen.Condition) *toolCommitDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t toolCommitDo) Select(conds ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t toolCommitDo) Where(conds ...gen.Condition) *toolCommitDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t toolCommitDo) Order(conds ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t toolCommitDo) Distinct(cols ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t toolCommitDo) Omit(cols ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t toolCommitDo) Join(table schema.Tabler, on ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t toolCommitDo) LeftJoin(table schema.Tabler, on ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t toolCommitDo) RightJoin(table schema.Tabler, on ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t toolCommitDo) Group(cols ...field.Expr) *toolCommitDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t toolCommitDo) Having(conds ...gen.Condition) *toolCommitDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t toolCommitDo) Limit(limit int) *toolCommitDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t toolCommitDo) Offset(offset int) *toolCommitDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t toolCommitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *toolCommitDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t toolCommitDo) Unscoped() *toolCommitDo {
	return t.withDO(t.DO.Unscoped())
}

func (t toolCommitDo) Create(values ...*model.ToolCommit) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t toolCommitDo) CreateInBatches(values []*model.ToolCommit, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t toolCommitDo) Save(values ...*model.ToolCommit) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t toolCommitDo) First() (*model.ToolCommit, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ToolCommit), nil
	}
}

func (t toolCommitDo) Take() (*model.ToolCommit, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ToolCommit), nil
	}
}

func (t toolCommitDo) Last() (*model.ToolCommit, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ToolCommit), nil
	}
}

func (t toolCommitDo) Find() ([]*model.ToolCommit, error) {
	result, err := t.DO.Find()
	return result.([]*model.ToolCommit), err
}

func (t toolCommitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ToolCommit, err error) {
	buf := make([]*model.ToolCommit, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t toolCommitDo) FindInBatches(result *[]*model.ToolCommit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t toolCommitDo) Attrs(attrs ...field.AssignExpr) *toolCommitDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t toolCommitDo) Assign(attrs ...field.AssignExpr) *toolCommitDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t toolCommitDo) Joins(fields ...field.RelationField) *toolCommitDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t toolCommitDo) Preload(fields ...field.RelationField) *toolCommitDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t toolCommitDo) FirstOrInit() (*model.ToolCommit, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ToolCommit), nil
	}
}

func (t toolCommitDo) FirstOrCreate() (*model.ToolCommit, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ToolCommit), nil
	}
}

func (t toolCommitDo) FindByPage(offset int, limit int) (result []*model.ToolCommit, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t toolCommitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t toolCommitDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t toolCommitDo) Delete(models ...*model.ToolCommit) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *toolCommitDo) withDO(do gen.Dao) *toolCommitDo {
	t.DO = *do.(*gen.DO)
	return t
}
